#!/usr/bin/php
<?php

const TEST_HOME = __DIR__;
const PORTAL_HOME = TEST_HOME . '/portal';
const DB_HOME = '/tmp/jars-test-db';
const VERBOSE = true;
const USERNAME = 'music';
const PASSWORD = '983dk32dfmfa1s';
const AUTH_RANDOM_BITS = '0a1d029281fc6623130266c76291e1162ce1d53e5e9a6b6f28d3a56796105249';

require TEST_HOME . '/lib.php';
require TEST_HOME . '/vendor/autoload.php';

shell_exec('rm -rf "' . DB_HOME . '"; mkdir "' . DB_HOME . '"');

try {
    require __DIR__ . '/all-tests.php';
} catch(TestFailedException $e) {
    echo "\n\n\n\n";
    echo "-------------------------\n";
    echo "        TEST FAILED      \n";
    echo "-------------------------\n";
    echo "\n";
    echo $e->getMessage() . "\n";
    echo "\n";
    echo "That's all we know...\n";
    echo "\n\n\n";

    die(1);
}
